### ISSUE TITLE
Uploads only as application or service scope.. not user scope

### ISSUE THREAD

**Issue by closedstack** [thelastofreed/PoshBox#1]
I have some user cases to give access to users without having Full Admin Access to the instance. For example a user/app being able to upload into it's own account. Using connect-box -id errors out

_connect-box -id "xxxxxxxxx" -path $credJSON
get-boxfolderitems  -folderid "0"_

I get an error:
> Exception calling "Wait" with "0" argument(s): "One or more errors occurred."
> At C:\Program Files\WindowsPowerShell\Modules\poshbox\1.0.44.0\poshbox.psm1:585 char:3
> +         $foldlist.Wait()
> +         ~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : AggregateException
>  
> get-boxfolderitems : Box.V2.Exceptions.BoxException: Bearer realm="Service", error="insufficient_scope", error_description="The request requires higher privileges 
> than provided by the access token."
> 

Although I can use the API using the SDK itself and it works:
```
$file = "$scriptLocation\test.json"
$userid = "1234567"
$json = Get-Content $file

#Create a Box instance
$iBoxConfig = [Box.V2.Config.BoxConfig]::CreateFromJsonString($json)
$JWTAuth = [Box.V2.JWTAuth.BoxJWTAuth]::new($iBoxConfig)

#Set the Authentication
$adminToken = $JWTAuth.AdminToken()
$adminclient = $JWTAuth.AdminClient($adminToken)

$ut = $adminclient.Auth.BoxJWTAuth.UserToken($userid)
$uc = $adminclient.Auth.BoxJWTAuth.UserClient($ut,$userid) 
$uc.FoldersManager.GetFolderItemsAsync(0,100,0).result.entries.name

```
So basically it seems that the module only gets the Admin Token, but not a user Token (and is trying to use As-User behind the scenes, which it doesn't have permissions to). If I don't specify an ID to connect-box, it will connect in the application context and upload the content to a folder that is no visible to the associated user account.

**Comment by thelastofreed** [comment]
@closedstack Sorry for the delayed response.  I don't know if you were encountering the error when using the previous version of the module, but your explanation as to why it is happening is not occurring for me.  I was able to loop through 5 box users at random, use connect-id to authenticate as the user, and return the items within each of their environments:
![image](https://user-images.githubusercontent.com/50460411/63321806-ce8f9780-c2ef-11e9-8a71-03cfbd4b24fc.png)
If you were using the latest version of the module, then the only reason that I can think of as to why it is happening for you is that the box app which generated the json that you use to authenticate to box was not configured correctly.  I created a tutorial demonstrating how the box app should be configured for the module to work correctly [here](https://github.com/thelastofreed/PoshBox#box-environment-configuration).  Give it a read.
